### ISSUE TITLE
JDBC

### ISSUE THREAD

**Issue by we4sz** [royclarkson/spring-rest-service-oauth#1]
Hi Roy!

So say i wan't to create an application with like 100 users with different user roles.
I want to create the users in a MySQL database and use them, I want also be able to "backtrace" an oath to see which privileges the user have. Would be awesome if you could show an example for this.

Thanks

//John

**Comment by raedobh** [comment]
@we4sz check this #15

**Comment by royclarkson** [comment]
Thanks to @raedobh, I think this is covered now.
