### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by Artgit** [royclarkson/spring-rest-service-oauth#16]
Thanks for an awesome example !

Could you please extend the source in order to work with oauth2 over https ?

Thanks in advance!

**Comment by mariubog** [comment]
https://github.com/royclarkson/spring-rest-service-oauth/pull/14

**Comment by Artgit** [comment]
@mariubog , thank you very much, that's exactly what I'm looking for !

Also, I have noticed "cookies.txt" in resources folder. What is the purpose of this file ?

**Comment by royclarkson** [comment]
#14 has been merged into master.
