### ISSUE TITLE
separate AuthorizationServer from ResourceServer(single sign-on)

### ISSUE THREAD

**Issue by Artgit** [royclarkson/spring-rest-service-oauth#17]
Could you pleae show an example where AuthorizationServer is separeted from ResourceServer.
For example I have two different web applications with REST API on different hosts and ports. I'd like to implement something like SSO(single sign-on) like a third application with a oauth2 over https protocol. 

The main question is how to link my existing web applications with the new oauth2 server ? What should be implemented on AuthorizationServer side and what should be implemented in the exisiting web applications in order to use SSO for these existing REST api.

**Comment by mariubog** [comment]
authorization server issues token, resource server provides access to resource based on that token but it has to have a way to validate it to confirm it is the token issued by authorization server, in royclarkson's example tokens are stored in memory `private TokenStore tokenStore = new InMemoryTokenStore();` by authentication server but it is within same application, when dealing with separate implementation you have to have a way to check from resource server agains that tokenstore in authentication server, how you establish that comunication when both are on separate hosts is up to you and it is probably way beyond the scope of this example

**Comment by Artgit** [comment]
@mariubog , thanks for your answer! 

Please let me summarize - I have two application - first is oauth2 AuthorizationServer(my SSO point) and the second application is some business REST service API. So, based of this example, I need to move implementation of ResourceServerConfiguration from first to my second application and implement some kind of shared TokenStore for both of them, for example based on persistent database ?

**Comment by mariubog** [comment]
whichever endpoints you want to secure with oauth thats where your resource server has to be, in you case REST endpoints, yes probably some kind of database and than provide secure endpoint to access that database and verify that token is valid, I have not done it but would suggest to take good look on both `AuthorizationServerEndpointsConfigurer` and `ResourceServerSecurityConfigurer` they offer some api to make lot of customizations, though communication will be still the part that is left to your own implementation

**Comment by Artgit** [comment]
@mariubog , thanks !

**Comment by royclarkson** [comment]
@mariubog thanks for the information! Agreed that it is beyond scope of this example.
