### ISSUE TITLE
Extend Oauth2 Example

### ISSUE THREAD

**Issue by ddymke** [royclarkson/spring-rest-service-oauth#25]
Hello out there,

currently I do my first steps with Spring Security. I started with the Oauth2 example project.
But I reached a point where one Oauth2Resource has to talk to another Resource.

I read a lot and tried even more, but I dont get it..
So would it possible to extend the example with another resource which just calls the exisiting resource with an Oauth2RestTemplate?

That would be awesome, thanks

**Comment by mariubog** [comment]
I wrote little example that works with Roy's `spring-rest-service-oauth`, here is the link
https://github.com/mariubog/oauth-client-sample, I am not sure if this is what you looking for though

**Comment by ddymke** [comment]
Sorry,  I posted in the wrong window >.< But I will give it a try, thanks

**Comment by mariubog** [comment]
No problem, the example I gave you uses `Oauth2RestTemplate` as the class to establish connection with oauth service

**Comment by royclarkson** [comment]
@mariubog thanks for sharing!
